megatron: fix MegatronPretrainingBatchSampler
9rum/flatflow pull request #17
Opened 2024-11-14 09:18 UTC by amo33

This PR fixes megatron_batch_sampler.py and some other codes as follows:

In __iter__, broadcasting indices and yielding indices were fixed by using torch.distributed.broadcast.
In __init__, **sizes** of dataset were calculated by flatflow.sys.getsizeof. 
In order to fix this issue, there was another code implemented as blendable_dataset.py

In blendable_dataset.py, __sizeof__ is implemented because samplers dataset was instance of BlendableDataset.

Lastly, BlendableDataset was added in megatron_gpt_sft_model.py and __init__.py. 

Moreover, there is one issue to work on megatron_batch_sampler.py in __init__ where we call self.client with Init. 
(Currently working on this and need help to fix this)

2024-11-23 12:44 UTC, amo33 commented
@9rum Other PR will be added within following week. 

- [ ] custom parallel state for model parallel group broadcast
- [ ] Profiler for forward time profile

2024-11-25 02:11 UTC, 9rum requested changes
@amo33 Thanks for filing this PR.
I have left several comments for minor improvements and formatting issues.
Always appreciate for your hard work.

2024-11-25 02:11 UTC, 9rum commented on flatflow/nemo/collections/nlp/data/language_modeling/megatron/megatron_batch_samplers.py
> +            if self.global_rank == 0:
I think these lines can be simplified to:
```python
self.client.Init(
    global_batch_size,
    micro_batch_size,
    order,
    self.data_parallel_rank,
    seed,
    heterogeneous,
    use_flat_shuffle,
    hidden_size,
    sizes if self.global_rank == 0 else None,
)
```

2024-11-25 02:11 UTC, 9rum commented on flatflow/nemo/collections/nlp/models/language_modeling/megatron_gpt_sft_model.py
> +                    size = num_train_samples_after_blend
Please use Ruff format.

2024-11-25 02:11 UTC, 9rum commented on flatflow/nemo/collections/nlp/data/language_modeling/megatron/megatron_batch_samplers.py
> +        end = False
I think ``end`` is not required and the below loop can be simplified to:
```python
while True:
    if self.consumed_samples > self.total_length // self.num_data_parallel_group:
        break
    ...
```

2024-11-25 02:49 UTC, amo33 commented
@9rum Thanks for your feedback,
PR is updated.

2024-11-25 08:03 UTC, 9rum approved these changes
LGTM

2024-11-25 08:03 UTC, merged