data: add unit test for index retriever.
9rum/flatflow pull request #2
Opened 2024-03-20 12:22 UTC by amo33

This PR adds test code checking whether retrieval process of a data sample is correct.
Output using ``make test`` :

```
Test project /home/flatflow/build
    Start 1: DatasetTest.Constructor
1/3 Test #1: DatasetTest.Constructor ...........   Passed    0.94 sec
    Start 2: DatasetTest.IntraBatchShuffling
2/3 Test #2: DatasetTest.IntraBatchShuffling ...   Passed    7.98 sec
    Start 3: DatasetTest.IndexRetriever
3/3 Test #3: DatasetTest.IndexRetriever ........   Passed    0.00 sec

100% tests passed, 0 tests failed out of 3

Total Test time (real) =   8.96 sec
```
Test log:

```
3/3 Testing: DatasetTest.IndexRetriever
3/3 Test: DatasetTest.IndexRetriever
Command: "/home/flatflow/build/flatflow/data/dataset_test" "--gtest_filter=DatasetTest.IndexRetriever"
Directory: /home/flatflow/build/flatflow/data
"DatasetTest.IndexRetriever" start time: Mar 20 12:19 UTC
Output:
----------------------------------------------------------
Running main() from /home/flatflow/third_party/googletest/googletest/src/gtest_main.cc
Note: Google Test filter = DatasetTest.IndexRetriever
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from DatasetTest
[ RUN      ] DatasetTest.IndexRetriever
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1710937155.765883   77368 dataset.h:130] Construction of inverted index took 0.000859 seconds
[       OK ] DatasetTest.IndexRetriever (0 ms)
[----------] 1 test from DatasetTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 1 test.
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"DatasetTest.IndexRetriever" end time: Mar 20 12:19 UTC
"DatasetTest.IndexRetriever" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Mar 20 12:19 UTC

```

2024-03-27 09:09 UTC, 9rum requested changes
@amo33 Thanks for filing this PR.
I have left a few comments, so please remind me after change.

2024-03-27 09:09 UTC, 9rum commented on flatflow/data/dataset_test.cc
> +  // Note:
Please use upper case for comments to be rendered - i.e., ``NOTE:`` instead of ``Note:``.

2024-03-28 03:40 UTC, amo33 commented
@9rum I have updated the code to address all the changes you suggested:
- Use ternary operator 
- Fix comment style
- Rename function, arguments

Let me know if any further changes are needed.

2024-03-28 05:31 UTC, amo33 commented on flatflow/data/dataset_test.cc
> +  inline std::size_t size(uint16_t size, bool checkItem = true) const noexcept {
Since **_items_** is already used as class dataset's member variable, I changed checkItem to item.

2024-03-28 06:04 UTC, 9rum approved these changes
LGTM

2024-03-28 06:05 UTC, merged